global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'orangeblood-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['orangeblood:8082']
        labels:
          application: 'orangeblood-app'